services:
  timescaledb:
    image: timescale/timescaledb:2.19.0-pg17
    container_name: timescaledb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5050:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
  pgadmin:
    image: dpage/pgadmin4:9.1.0
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5051:80"
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    restart: always